package com.mashreq.paymentTracker.exception;

public interface ExceptionCodes {
	int DEFAULT_EXCEPTION_CODE = 100;
	int USER_UPDATE_FAILURE = 103;
	int APPLCATION_LOAD_EXCEPTION_CODE = 101;
	int DATE_PARSE_EXCEPTION = 102;
	int INVALID_LINK_EXCEPTION = 10201;
	int JSON_MARSHALL_EXCEPTION = 10202;
	int ENTITY_NOTFOUND__EXCEPTION = 10203;
	int DATE_FORMATE_EXCEPTION = 10204;
	int NO_RESULT_FOUND_EXCEPTION = 10205;
	int REPORT_MATRICS_FETCH_FAILURE_EXCEPTION = 10206;
	int REPORT_NOTFOUND_EXCEPTION = 10207;
	int REPORT_INSATNCE_INSERT_EXCEPTION = 10208;
	int REPORT_DATA_NOTFOUND_EXCEPTION = 10209;
	int REPORT_PROMPTS_POPULATE_EXCEPTION = 10210;
	int REPORT_INSTANCE_POPULATE_EXCEPTION = 10211;

	int THREAD_INTERRUPT_EXCEPTION = 10101;
	int THRED_EXECUTION_TIME_OUT_EXCEPTION = 10102;
	int REPORT_EXECUTION_EXCEPTION = 10103;
	int DATE_VALUE_OUT_OF_RANGE_EXCEPTION_FAILURE_CODE = 10104;
	int INVALID_BANK_REF_NO_EXCEPTION_FAILURE_CODE = 10105;

	int SQL_CONNECTION_EXCEPTION = 10905;
	int SQL_DATASOURCE_EXCEPTION = 10906;
	int SQL_DRIVER_CLASS_NOT_FOUND_EXCEPTION = 10907;
	int RESULT_SET_ERROR = 10908;
	int REPORT_EXECUTION_QUERY_EXECUTION_FAILURE = 99999;

	int REPORT_EXPORT_PDF_MALFORMED_URL_FAILURE_CODE = 99878;
	int REPORT_EXPORT_PDF_DOCUMENT_CREATION_FAILURE_CODE = 99879;
	int REPORT_EXPORT_FILE_OPERATION_FAILURE_CODE = 99880;
	int REPORT_EXPORT_TRANSFORMER_CONFIGURATION_FAILURE_CODE = 99881;
	int REPORT_EXPORT_WORD_INVALID_FORMAT_ERROR_CODE = 99882;
	int REPORT_EXPORT_PARSER_CONFIGURATION_FAILURE_CODE = 99883;
	int REPORT_EXPORT_SAX_FAILURE_CODE = 99884;
	int SIMPLE_DATE_PARSE_EXCEPTION_CODE = 99885;
	int LINK_RETRIVAL_EXCEPTION = 99886;

	int EDMS_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20201;
	int FLEX_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20202;
	int FLEX_ARCHIVAL_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20203;
	int SWIFT_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20204;
	int UAEFTS_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20205;
	int KNPS_TRANSACTION_SUMMARY_EXECUTOR_FAILURE_EXCEPTION = 20206;

	int EDMS_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20206;
	int FLEX_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20207;
	int FLEX_ARCHIVAL_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20208;
	int MATRIX_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20209;
	int SWIFT_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20210;
	int UAEFTS_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20211;
	int KNPS_ACTIVITY_DETAILS_EXECUTOR_FAILURE_EXCEPTION = 20212;

	int RESOURCES_CLOSING_FAILED = 10801;

	int REPORT_EXECUTION_JOB_SCHEDULING_FAILURE_CODE = 99876;
	int REPORT_EXECUTION_JOB_SCHEDULING_VALIDATION_FAILURE_CODE = 99877;
	int REPORT_SCHEDULE_SERIALIZATION_FAILURE_CODE = 99876;
	int REPORT_EXECUTION_FAILURE_DEFAULT_CODE = 99881;
	int REPORT_EXECUTION_INPUT_VALIDATION_FAILED = 99998;

	int REPORT_EXECUTION_OPERATIONAL_STATUS_UPDATE_FAILURE_CODE = 99890;

}
