CREATE TABLE [dbo].[QUEUEVIEWTRK](
	[PROCESSINSTANCEID] [nvarchar](255) NULL,
	[PROCESSNAME] [nvarchar](255) NULL,
	[ACTIVITYNAME] [nvarchar](255) NULL,
	[INTRODUCTIONDATETIME] [datetime] NULL
) ON [PRIMARY]
GO

