create table conf_rpt_comp
(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   report_id NUMBER
   NOT NULL,
   component_name varchar (500) NOT NULL,
   component_key varchar (500) NOT NULL,
   active varchar (1) NOT NULL,
   CONSTRAINT pk_rpt_comp_id PRIMARY KEY (id),
   CONSTRAINT conf_rpt_comp_report_id_fkey FOREIGN KEY (report_id) REFERENCES conf_report (id)
);