CREATE TABLE conf_comp_country
(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   rept_comp_id NUMBER
   NOT NULL,
   country varchar (200) NOT NULL,
   data_source_id NUMBER NOT NULL,
   CONSTRAINT conf_comp_country_pkey PRIMARY KEY (id),
   CONSTRAINT conf_source_query_data_source_id_fkey FOREIGN KEY (data_source_id) REFERENCES conf_data_source (id),
   CONSTRAINT conf_source_query_rept_comp_id_fkey FOREIGN KEY (rept_comp_id) REFERENCES conf_rpt_comp
);