CREATE TABLE conf_data_source
(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   ds_name varchar (500) not null,
   ds_description varchar (2000) NULL,
   ds_provider NUMBER not null,
   ds_username varchar (100) not null,
   ds_password NVARCHAR2 (255) not null,
   password_encrypted NVARCHAR2 (255) not null,
   server_ip NVARCHAR2 (200) not null,
   ds_port NUMBER not null,
   ds_schema_name NVARCHAR2 (250) not null,
   ds_owner NVARCHAR2 (250) not null,
   active varchar (1) not null,
   ds_country varchar (255) null,
   CONSTRAINT pk_ds_id PRIMARY KEY (id)
);