CREATE TABLE conf_metric
(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   display_name varchar (500) NOT NULL,
   metrics_order NUMBER NOT NULL,
   report_id NUMBER NOT NULL,
   display VARCHAR (1) NOT NULL,
   ent_id NUMBER NULL,
   CONSTRAINT pk_metrics_id PRIMARY KEY (id)
);