create table conf_module
(
   id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   mod_name VARCHAR (200) not null,
   display_name VARCHAR (500) not null,
   mod_description VARCHAR (1000) not null,
   active VARCHAR (1) not null,
   valid VARCHAR (1) null,
   error varchar (500),
   warning varchar (500),
   CONSTRAINT pk_conf_module_id PRIMARY KEY (id)
)