CREATE TABLE conf_prompt
(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   pr_key varchar (100) NOT NULL,
   display_name varchar (500) NOT NULL,
   pr_order NUMBER NOT NULL,
   pr_required varchar (1) NOT NULL,
   report_id NUMBER NOT NULL,
   ent_id NUMBER NULL,
   CONSTRAINT pk_prompt_id PRIMARY KEY (id),
   constraint conf_prompt_report_id_fkey FOREIGN KEY (report_id) REFERENCES conf_report (id)
);