CREATE TABLE [dbo].[EDMS_QUERY](
	[REPORT_NAME] [varchar](255) NULL,
	[QUERY_KEY] [varchar](255) NULL,
	[QUERY] [varchar](max) NULL,
	[TABLE_NAME] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

